# Generated by Django 6.0.1 on 2026-01-19 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Categorys', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=150)),
                ('img_add', models.ImageField(blank=True, default='imges/default.png', null=True, upload_to='imges')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='task.category')),
                ('participants', models.ManyToManyField(blank=True, related_name='RBAC', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
