# Generated by Django 6.0 on 2026-01-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_participant_event_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
