# Generated by Django 6.0 on 2026-01-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img_add',
            field=models.ImageField(blank=True, upload_to='imges'),
        ),
    ]
