# Generated by Django 6.0 on 2026-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_event_img_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_add',
            field=models.ImageField(blank=True, default='imges/default.png', null=True, upload_to='imges'),
        ),
    ]
