# Generated by Django 6.0 on 2026-01-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_event_img_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
