# Generated by Django 6.0.1 on 2026-01-30 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Bangladeshi format: +8801XXXXXXXXX', regex='^\\+?8801[3-9]\\d{8}$')]),
        ),
    ]
